import '@radix-ui/themes/styles.css'

import '../styles/style.css'
import '../styles/theme.css'

import { Inter } from 'next/font/google'
import { Theme as RadixTheme } from '@radix-ui/themes'

import { Header } from '@/components/layout/header'
import * as Container from '@/components/layout/container'
import { ApplyModal } from '@/app/apply-modal'

const inter = Inter({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <Container.Body>
          <RadixTheme hasBackground={false}>
            <Header />
            <Container.Content>{children}</Container.Content>
            <ApplyModal />
          </RadixTheme>
        </Container.Body>
      </body>
    </html>
  )
}
